# Generated by Django 6.0.7 on 2026-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('GERANT', 'Gérant'), ('CAISSIER', 'Caissier'), ('SERVEUR', 'Serveur'), ('CUISINIER', 'Cuisinier'), ('LIVREUR', 'Livreur'), ('VENDEUR', 'Vendeur'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
