# Generated by Django 6.0.7 on 2026-08-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_photogalerie_temoignage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='repondu_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reponse',
            field=models.TextField(blank=True, default=''),
        ),
    ]
