# Generated by Django 6.0.7 on 2026-08-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
