# Generated by Django 6.0.7 on 2026-08-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
        ('ventes', '0003_vente_annule_le_vente_annule_par_vente_annulee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='remise_pourcent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='tables.table', verbose_name='Table'),
        ),
    ]
