# Generated by Django 6.0.7 on 2026-08-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_vente_remise_pourcent_vente_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='monnaie_rendue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monnaie rendue'),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_recu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant reçu'),
        ),
        migrations.AddField(
            model_name='vente',
            name='type_commande',
            field=models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('EMPORTER', 'À emporter'), ('LIVRAISON', 'Livraison')], default='SUR_PLACE', max_length=20, verbose_name='Type de commande'),
        ),
    ]
