# Generated by Django 6.0.7 on 2026-08-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_vente_monnaie_rendue_vente_montant_recu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='type_commande',
            field=models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('A_EMPORTER', 'À emporter'), ('LIVRAISON', 'Livraison')], default='SUR_PLACE', max_length=20, verbose_name='Type de commande'),
        ),
    ]
