# Generated by Django 6.0.7 on 2026-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_commande_type_a_emporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='latitude_client',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude_client',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='nom_client_livraison',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nom du client (livraison)'),
        ),
    ]
