# Generated by Django 6.0.7 on 2026-08-07 19:56

import secrets

from django.db import migrations, models


def attribuer_tokens(apps, schema_editor):
    Commande = apps.get_model("commandes", "Commande")
    for commande in Commande.objects.filter(token="").iterator():
        commande.token = secrets.token_urlsafe(32)
        commande.save(update_fields=["token"])


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_gps_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Jeton de suivi secret'),
        ),
        migrations.RunPython(attribuer_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='commande',
            name='token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, unique=True, verbose_name='Jeton de suivi secret'),
        ),
    ]
