# Generated by Django 6.0.7 on 2026-08-11 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_commande_token'),
        ('ventes', '0004_vente_remise_pourcent_vente_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='payee',
            field=models.BooleanField(default=False, verbose_name='Payée'),
        ),
        migrations.AddField(
            model_name='commande',
            name='payee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payée le'),
        ),
        migrations.AddField(
            model_name='commande',
            name='vente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande', to='ventes.vente', verbose_name='Vente liée'),
        ),
    ]
