# Generated by Django 6.0.7 on 2026-08-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_remove_parametrerestaurant_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrerestaurant',
            name='fermeture_midi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='fermeture_soir',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='jours_ouverture',
            field=models.CharField(blank=True, default='Lundi au Dimanche', max_length=50),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='ouverture_midi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='ouverture_soir',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
