# Generated by Django 6.0.7 on 2026-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_parametrerestaurant_fermeture_midi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrerestaurant',
            name='email_expediteur',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='smtp_mot_de_passe',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='smtp_utilisateur',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='url_site',
            field=models.URLField(blank=True, default=''),
        ),
    ]
