# Generated by Django 6.0.7 on 2026-08-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_parametrerestaurant_email_expediteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrerestaurant',
            name='impression_silencieuse',
            field=models.BooleanField(default=False),
        ),
    ]
