# Generated by Django 6.0.7 on 2026-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_parametrerestaurant_impression_silencieuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrerestaurant',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='image_fond',
            field=models.ImageField(blank=True, null=True, upload_to='parametres/', verbose_name='Image de fond du site'),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parametrerestaurant',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
