# Generated by Django 6.0.7 on 2026-08-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_parametrerestaurant_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrerestaurant',
            name='tiktok',
            field=models.URLField(blank=True, default=''),
        ),
    ]
